In [3]:
import numpy as np

In [4]:
arr2D = np.array([[1,2,3], [2,3,4]])
arr1D = np.array([3,4,5])

In [5]:
arr2D

array([[1, 2, 3],
       [2, 3, 4]])

In [13]:
arr2D.ndim

2

In [14]:
arr2D.shape

(2, 3)

In [6]:
arr1D

array([3, 4, 5])

In [15]:
arr1D.ndim

1

In [16]:
arr1D.shape

(3,)

In [7]:
# operasi numpy array
arr2D + arr1D

array([[4, 6, 8],
       [5, 7, 9]])

In [8]:
arr2D - arr1D

array([[-2, -2, -2],
       [-1, -1, -1]])

In [9]:
arr2D * arr1D

array([[ 3,  8, 15],
       [ 6, 12, 20]])

In [10]:
# tidak sama dengan matriks antara numpy array. untuk matriks
matriks2D = np.matrix([[1,2,3], [2,3,4]])
matriks1D = np.matrix([3,4,5])

In [12]:
matriks2D * matriks1D

ValueError: shapes (2,3) and (1,3) not aligned: 3 (dim 1) != 1 (dim 0)

In [17]:
# kalau mau bisa, diubah menjadi seperti dibawah
matriks2D_edit = np.matrix([[1,2,3], [2,3,4]])
matriks1D_edit = np.matrix([[3],[4],[5]])

In [18]:
matriks1D_edit.ndim

2

In [19]:
matriks1D_edit.shape

(3, 1)

In [20]:
# maka sekarang bisa dilakukan operasi perkalian matrix
matriks2D_edit * matriks1D_edit

matrix([[26],
        [38]])

In [23]:
matriks2D_edit.dot(matriks1D_edit)

matrix([[26],
        [38]])

In [21]:
# namun hasilnya ini akan berbeda, jika kita lakukan dengan numpy array
numpy2D_edit = np.array([[1,2,3], [2,3,4]])
numpy1D_edit = np.array([3,4,5])

In [22]:
numpy2D_edit.dot(numpy1D_edit)

array([26, 38])

In [24]:
# untuk diketahui berapa baris, berapa kolom
numpy2D_edit.shape

(2, 3)

In [25]:
# mengetahui berapa elemen
numpy2D_edit.size

6

In [26]:
numpy2D_edit.reshape(3, 2)

array([[1, 2],
       [3, 2],
       [3, 4]])

In [27]:
numpy1D_edit.shape

(3,)

In [28]:
numpy2D_edit * numpy1D_edit

array([[ 3,  8, 15],
       [ 6, 12, 20]])

In [29]:
numpy2D_edit

array([[1, 2, 3],
       [2, 3, 4]])

In [30]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [31]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [32]:
# array linear
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [33]:
# array linear space
np.linspace(1,10,6) # parameter terakhir bukan step, tapi isinya jumlah elemennya ada berapa

array([ 1. ,  2.8,  4.6,  6.4,  8.2, 10. ])

In [36]:
numpy2D_edit.dtype

dtype('int32')

In [37]:
numpy2D_edit.astype('float64')

array([[1., 2., 3.],
       [2., 3., 4.]])

In [38]:
np.random.random((3,3)) # parameternya ukuran arraynya

array([[0.18475735, 0.4121852 , 0.68411756],
       [0.91605644, 0.66993598, 0.99029759],
       [0.40542855, 0.05846658, 0.27630708]])

In [39]:
np.random.randint(0,10,5)

array([9, 7, 5, 9, 0])

In [43]:
np.random.randint(0,10,(3,3))

array([[6, 8, 5],
       [8, 5, 5],
       [3, 5, 1]])

In [44]:
# untuk statistik
numpy2D_edit.min()

1

In [45]:
numpy2D_edit.max()

4

In [46]:
numpy2D_edit.mean()

2.5

In [47]:
numpy2D_edit.std()

0.9574271077563381

In [48]:
numpy2D_edit.var()

0.9166666666666666